services:
  server:
    build:
      context: .
    ports:
      - 80:80
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=default_database
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "--dbname=default_database", "--username=user" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db-data:
networks:
  db:
    driver: bridge

