spring:
  datasource:
    url: jdbc:postgresql://db:5432/default_database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
