spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: /WEB-INF/templates/
    suffix: .html
